config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users
  root to: "items#index"
  post 'toggle_card_list', to: 'orders#toggle_card_list'
  resources :items do
    member do
      post   'like' => 'likes#like',   as: 'like'
      delete 'unlike' => 'likes#unlike', as: 'unlike'
    end
    resources :comments, only: :create
    resources :orders, only: [:index, :create] do
      collection do
        get 'refresh_card_frame'
        post 'set_card'
        post 'clear_session'
      end
    end
  end
  resources :users, only: :show do
    resources :cards, only: [:index, :new, :create, :destroy] do
      member do
        post 'set_default'
      end
    end
    member do
      get :likes
      get 'items'
      get 'orders'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  attr_accessor :token

  validates :token, presence: true, on: :create
  encrypts :brand, :last4, :exp_month, :exp_year

  # Expiration Date Check
  def expired?
    Date.new(exp_year.to_i, exp_month.to_i, 1) < Date.today
  end
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'メンズ' },
    { id: 3, name: 'レディース' },
    { id: 4, name: 'ベビー・キッズ' },
    { id: 5, name: 'インテリア・住まい・小物' },
    { id: 6, name: '本・音楽・ゲーム' },
    { id: 7, name: 'おもちゃ・ホビー・グッズ' },
    { id: 8, name: '家電・スマホ・カメラ' },
    { id: 9, name: 'スポーツ・レジャー' },
    { id: 10, name: 'ハンドメイド' },
    { id: 11, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '新品・未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :info, :images, presence: true
  validates :images, length: { minimum: 1, maximum: 5, message: 'は1枚以上5枚以下にしてください' }
  validates :price, presence: true,
                    numericality: {
                      only_integer: true,
                      greater_than_or_equal_to: 300,
                      less_than_or_equal_to: 9_999_999
                    }

  belongs_to :user
  has_one :order
  has_many_attached :images
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition
  belongs_to :postage_type
  belongs_to :prefecture
  belongs_to :shipping_time

  validates :category_id, :condition_id, :postage_type_id, :prefecture_id,
            :shipping_time_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item, counter_cache: :likes_count
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :address

end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :postal_code,
                :prefecture_id,
                :city,
                :block,
                :building,
                :phone_number,
                :item_id,
                :user_id,
                :card_id

  with_options presence: true do
    validates :user_id
    validates :item_id
    validates :card_id
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is invalid. Enter it as follows (e.g. 123-4567)' }
    validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :city
    validates :block
    validates :phone_number, length: { in: 10..11, too_short: 'is too short', too_long: 'is too long' },
                             format: { with: /\A[0-9]+\z/, message: 'is invalid. Input only numbers' }
  end

  def save
    order = Order.create(item_id:, user_id:)
    Address.create(postal_code:, prefecture_id:, city:, block:, building:,
                   phone_number:, order_id: order.id)
  end
end

app/models/postage_type.rb
class PostageType < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '着払い(購入者負担)' },
    { id: 3, name: '送料込み(出品者負担)' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/shipping_time.rb
class ShippingTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1~2日で発送' },
    { id: 3, name: '2~3日で発送' },
    { id: 4, name: '4~7日で発送' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  validates :birthday, presence: true

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ } do
    validates :first_name
    validates :last_name
  end

  with_options presence: true, format: { with: /\A[ァ-ヶー]+\z/ } do
    validates :first_name_kana
    validates :last_name_kana
  end

  has_many :items
  has_many :orders
  has_many :cards, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_items, through: :likes, source: :item
  has_many :comments
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def sidebar_link(name, path)
    class_name = 'section'
    class_name << ' active' if current_page?(path)

    content_tag :li, class: class_name do
      link_to name, path, class: 'section_name'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FurimaKagawa2023SetouchiTitans</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <!-- Pay.jp script -->
    <script src="https://js.pay.jp/v2/pay.js"></script>
    <!-- end: Pay.jp script -->
  </head>

  <body>
    <%= turbo_frame_tag 'modal' %>
    <%= turbo_frame_tag "flash" do %>
      <%= render 'shared/flash_messages' %>
    <% end %>
    <% if content_for?(:header) %>
      <%= yield :header %>
    <% else %>
      <%= render 'shared/header' %>
    <% end %>
    <% if content_for?(:sidebar) %>
      <div class="mypage">
        <div class="sidebar">
          <%= yield :sidebar %>
        </div>
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FurimaKagawa2023SetouchiTitans</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />
    <script type="text/javascript" src="https://js.pay.jp/v2/pay.js"></script>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="mypage">
      <div class="sidebar">
        <%= render 'shared/sidebar' %>
      </div>
      <div class="content">
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="<%= flash_class(type) %>">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<%#
  <div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
%>
<%#= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
<%#= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
<%#
  </div>
  </div>
%>
<%# /下部広告部分 %>

<div class="footer">
  <div class="footer-contents">
    <div class="furima-details">
      <h2 class="footer-content-head">FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', '#', class: 'footer-link' %></li>
        <li><%= link_to 'プライバシーポリシー', '#', class: 'footer-link' %></li>
        <li><%= link_to 'FURIMA利用規約', '#', class: 'footer-link' %></li>
        <li><%= link_to 'ポイントに関する特約', '#', class: 'footer-link' %></li>
      </ul>
    </div>
    <div class="furima-details">
      <h2 class="footer-content-head">FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', '#', class: 'footer-link' %></li>
        <li><%= link_to 'ブランド一覧', '#', class: 'footer-link' %></li>
      </ul>
    </div>
    <div class="furima-details">
      <h2 class="footer-content-head">FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', '#', class: 'footer-link' %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', '#', class: 'footer-link' %></li>
        <li><%= link_to 'お知らせ', '#', class: 'footer-link' %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag('furima-logo-white.png', class: 'logo-white'), '#' %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class="top-page-header">
  <div class="search-bar-contents">
    <%= link_to image_tag('furima-logo-color.png', class: 'furima-icon'), '/' %>
    <form class="search-form" action="#">
      <input class="input-box" placeholder="キーワードから探す" />
      <button class="search-button">
        <%= image_tag 'search.png', class: 'search-icon' %>
      </button>
    </form>
  </div>
  <div class="nav">
    <ul class="lists-left">
      <li><%= link_to 'カテゴリー', '#', class: 'category-list' %></li>
      <li><%= link_to 'ブランド', '#', class: 'brand-list' %></li>
    </ul>
    <ul class="lists-right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: 'user-nickname' %></li>
        <li>
          <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'logout' %>
        </li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: 'login' %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: 'sign-up' %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div
    data-controller="modal"
    data-action="keyup@document->modal#handleKeyup"
    class="fixed inset-0 z-10 overflow-y-auto"
    aria-labelledby="modal-title"
    role="dialog"
    aria-modal="true"
  >
    <div class="flex items-center justify-center min-h-screen px-4 text-center sm:block sm:p-0">
      <div
        data-action="click->modal#close"
        data-modal-target="wrapper"
        data-transition-end="ease-out duration-300"
        data-transition-enter-start="opacity-0"
        data-transition-enter-end="opacity-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100"
        data-transition-leave-end="opacity-0"
        class="fixed inset-0 transition-opacity bg-black bg-opacity-75"
        aria-hidden="true"
      ></div>

      <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

      <div
        data-modal-target="body"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        data-transition-enter-end="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        class="inline-block w-full px-4 pt-5 pb-4 overflow-hidden text-left align-bottom transition-all transform bg-white rounded-lg shadow-xl min-w-max sm:my-8 sm:align-middle sm:max-w-md sm:p-6"
      >
        <%= turbo_frame_tag "modal-body" do %>
          <%= yield %>
        <% end %>
        <p class="mt-4 text-center">
          <span class="text-xs">Powered by </span><span class="font-medium">PAY</span><span>.JP</span>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <ul class="sidebar-nav">
    <%= sidebar_link('プロフィール', user_path(@user)) %>
    <%= sidebar_link('いいね！一覧', likes_user_path(@user)) %>
    <%= sidebar_link('出品した商品', items_user_path(@user)) %>
    <%= sidebar_link('購入履歴', orders_user_path(@user)) %>
    <%= sidebar_link('クレジットカード一覧', user_cards_path(@user)) %>
  </ul>
</div>