config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users
  root to: "items#index"
  post 'toggle_card_list', to: 'orders#toggle_card_list'
  resources :items do
    member do
      post   'like' => 'likes#like',   as: 'like'
      delete 'unlike' => 'likes#unlike', as: 'unlike'
    end
    resources :comments, only: :create
    resources :orders, only: [:index, :create] do
      collection do
        get 'refresh_card_frame'
        post 'set_card'
        post 'clear_session'
      end
    end
  end
  resources :users, only: :show do
    resources :cards, only: [:index, :new, :create, :destroy] do
      member do
        post 'set_default'
      end
    end
    member do
      get :likes
      get 'items'
      get 'orders'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :address

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:index, :create]
  before_action :item_existence_check, only: [:index, :create]
  before_action :set_user, only: [:index, :create]
  before_action :set_cards, only: [:index, :create, :toggle_card_list, :refresh_card_frame]
  before_action :set_selected_card, only: [:index, :create, :set_card, :toggle_card_list, :refresh_card_frame]
  before_action :check_if_sold, only: :index
  before_action :contributor_check, only: :index

  def index
    @order_address = OrderAddress.new
    return if session[:selected_card_id]

    session[:selected_card_id] = @default_card&.id
  end

  def create
    @order_address = OrderAddress.new(order_params)
    if @order_address.valid?
      pay_item
      @order_address.save
      session.delete(:selected_card_id)
      redirect_to root_path
    else
      render 'index', status: :unprocessable_entity
    end
  end

  def set_card
    session[:selected_card_id] = params[:selected_card_id]
    render json: { message: 'Payment method set successfully.' }
  end

  def toggle_card_list
    @show_card_list = ActiveModel::Type::Boolean.new.cast(params[:show_card_list])

    respond_to(&:turbo_stream)
  end

  def refresh_card_frame
    respond_to(&:turbo_stream)
  end

  def clear_session
    session.delete(:selected_card_id)
    head :ok
  end

  private

  def order_params
    params.require(:order_address).permit(:postal_code, :prefecture_id, :city, :block, :building, :phone_number).merge(
      item_id: params[:item_id], user_id: current_user.id, card_id: @selected_card
    )
  end

  def set_item
    @item = Item.find_by(id: params[:item_id])
  end

  def set_cards
    @cards = current_user.cards
    @default_card = current_user.cards.find_by(is_default: true)
    gon.default_card = @default_card
  end

  def set_selected_card
    @selected_card =   current_user.cards.find_by(id: session[:selected_card_id]) ||
                       current_user.cards.find_by(is_default: true)
  end

  def set_user
    @user = current_user
  end

  def pay_item
    @item.with_lock do
      Payjp.api_key = ENV['PAYJP_SECRET_KEY']
      payjp_customer = Payjp::Customer.retrieve(current_user.payjp_customer_id)
      selected_card_id = @selected_card
      card = current_user.cards.find_by(id: selected_card_id)

      if card.present?
        Payjp::Charge.create(
          amount: @item.price, # 商品の値段
          customer: payjp_customer, # カードトークン
          card: card.card_id,
          currency: 'jpy' # 通貨の種類（日本円）
        )
      end
    end
  end

  def check_if_sold
    redirect_to root_path if @item.order.present?
  end

  def item_existence_check
    redirect_to root_path if @item.nil?
  end

  def contributor_check
    redirect_to root_path if current_user == @item.user
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_card_list.html.erb
<div class="text-center">
  <%= form_with url: '#', id: 'card-selection-form', method: :patch, local: true, html: { autocomplete: "off" }, data: { action: "submit->checkout#closeCardList" } do |form| %>
    <ul id="cards-container" class="grid w-full gap-3">
      <% @cards.each do |card| %>
        <li class="<%= 'expired' if card.expired? %>">
          <%=
            radio_button_tag 'card',
                             card.id,
                             card == @selected_card,
                             class: 'hidden peer',
                             data: {
                               card_selector_target: 'cardSelectionRadio',
                               action: 'change->checkout#setPaymentMethod',
                             }
          %>
          <%= label_tag "card_#{card.id}",
          class: "inline-flex items-center w-full max-w-lg p-5 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer justify-evenly dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700" do %>
            <%= fa_icon "cc-#{card.brand.downcase} 3x" %>
            <div class="block">
              <div class="w-full text-lg font-semibold"><%= "**** **** **** #{card.last4}" %></div>
              <div class="w-full">Expires on <%= card.exp_month %>/<%= card.exp_year %></div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <%=
    link_to fa_icon('plus 2x', text: 'Add New Card'),
            new_user_card_path(current_user, context: 'orders_card_list'),
            class:
              'inline-flex items-center w-full max-w-lg p-5 mt-3 text-2xl font-semibold text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer justify-evenly dark:hover:text-gray-300 dark:border-gray-700 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700',
            data: {
              turbo_frame: 'modal',
            }
  %>
  <%=
    button_to 'Confirm',
              toggle_card_list_path(show_card_list: !@show_card_list),
              method: :post,
              class:
                'inline-flex items-center justify-center w-full max-w-sm p-3 mt-3 text-lg font-semibold text-white bg-blue-500 border border-blue-500 rounded-lg cursor-pointer hover:bg-blue-700 focus:ring-4 focus:ring-blue-300',
              data: {
                turbo_frame: 'card_frame',
              }
  %>
</div>

app/views/orders/_new_card.html.erb
<li class="card-item <%= 'expired' if @card.expired? %>">
  <%=
    radio_button_tag 'card',
                     @card.id,
                     @card == @selected_card,
                     class: 'hidden peer',
                     data: {
                       card_selector_target: 'cardSelectionRadio',
                       action: 'change->checkout#setPaymentMethod',
                     }
  %>
  <%= label_tag "card_#{@card.id}",
          class: "inline-flex items-center w-full max-w-lg p-5 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer justify-evenly dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700" do %>
    <%= fa_icon "cc-#{@card.brand.downcase} 3x" %>
    <div class="block">
      <div class="w-full text-lg font-semibold"><%= "**** **** **** #{@card.last4}" %></div>
      <div class="w-full">Expires on <%= @card.exp_month %>/<%= @card.exp_year %></div>
    </div>
  <% end %>
</li>

app/views/orders/_selected_card.html.erb
<div class="text-center">
  <div
    data-checkout-target="selectedCard"
    class="inline-flex items-center w-full max-w-lg p-5 text-gray-500 bg-white border border-gray-200 rounded-lg justify-evenly dark:border-gray-700 dark:text-gray-400 dark:bg-gray-800"
  >
    <%= fa_icon "cc-#{selected_card.brand.downcase} 3x" %>
    <div class="block">
      <div class="w-full text-lg font-semibold"><%= "**** **** **** #{@selected_card.last4}" %></div>
      <div class="w-full">Expires on <%= @selected_card.exp_month %>/<%= @selected_card.exp_year %></div>
    </div>
  </div>
  <%=
    button_to fa_icon('refresh 2x', text: 'Change Card', class: 'pr-4'),
              toggle_card_list_path(show_card_list: !@show_card_list),
              class:
                'inline-flex items-center justify-center w-full max-w-sm p-3 mt-3 text-lg font-semibold text-white bg-blue-500 border border-blue-500 rounded-lg cursor-pointer hover:bg-blue-700 focus:ring-4 focus:ring-blue-300',
              method: :post,
              data: {
                turbo_frame: 'card_frame',
              }
  %>
</div>

app/views/orders/index.html.erb
<% content_for :header do %>
<%= render 'shared/second-header' %>
<% end %>

  <div class="transaction-contents">
    <div class="transaction-main">
      <h1 class="transaction-title-text">購入内容の確認</h1>
      <%# 購入内容の表示 %>
      <div class="buy-item-info">
        <%= image_tag(@item.images[0], class: 'buy-item-img') %>
        <div class="buy-item-right-content">
          <h2 class="buy-item-text">
            <%= @item.name %>
          </h2>
          <div class="buy-item-price">
            <p class="item-price-text">¥<%= @item.price %></p>
            <p class="item-price-sub-text"><%= @item.postage_type.name %></p>
          </div>
        </div>
      </div>
      <%# /購入内容の表示 %>

      <%# 支払額の表示 %>
      <div class="item-payment">
        <h1 class="item-payment-title">支払金額</h1>
        <p class="item-payment-price">¥<%= @item.price %></p>
      </div>
      <%# /支払額の表示 %>

      <%= include_gon %>

      <div class="payment-method">
        <h2 class="p-5 font-bold text-center">Payment method</h2>
        <div data-controller="checkout" data-checkout-set-card-url-value="<%= set_card_item_orders_path(item_id: @item.id) %>" data-checkout-clear-session-url-value="<%= clear_session_item_orders_path(item_id: @item.id) %>" data-checkout-refresh-card-frame-url-value="<%= refresh_card_frame_item_orders_path(item_id: @item.id) %>" >
          <%= turbo_frame_tag "card_frame" do %>
            <% if @cards.present? %>
              <% if @show_card_list %>
                <%= render 'card_list', locals: { cards: @cards, selected_card: @selected_card } %>
              <% else %>
                <%= turbo_frame_tag "selected-card" do %>
                  <%= render 'selected_card', selected_card: @selected_card %>
                <% end %>
            <% end %>
          <% else %>
            <%= turbo_frame_tag "selected-card" do %>
            <div class="text-center">
            <%= link_to fa_icon('plus 2x', text: 'Add New Card'),
                        new_user_card_path(current_user, context: 'orders_top'),
                        class: 'inline-flex items-center w-full max-w-lg p-5 text-2xl font-semibold text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer justify-evenly dark:hover:text-gray-300 dark:border-gray-700 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700',
                        data: { turbo_frame: 'modal'} %>
            </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

      <%= form_with model: @order_address, url: item_orders_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
        <%= render 'shared/error_messages', model: @order_address %>

        <%# 配送先の入力 %>
        <div class="shipping-address-form">
          <h1 class="info-input-haedline">配送先入力</h1>
          <div class="form-group">
            <div class="form-text-wrap">
              <label class="form-text">郵便番号</label>
              <span class="indispensable">必須</span>
            </div>
            <%=
              f.text_field :postal_code,
                           class: 'input-default',
                           id: 'postal-code',
                           placeholder: '例）123-4567',
                           maxlength: '8'
            %>
          </div>
          <div class="form-group">
            <div class="form-text-wrap">
              <label class="form-text">都道府県</label>
              <span class="indispensable">必須</span>
            </div>
            <%=
              f.collection_select(
                :prefecture_id,
                Prefecture.all,
                :id,
                :name,
                {},
                { class: 'select-box', id: 'prefecture' },
              )
            %>
          </div>
          <div class="form-group">
            <div class="form-text-wrap">
              <label class="form-text">市区町村</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :city, class: 'input-default', id: 'city', placeholder: '例）横浜市緑区' %>
          </div>
          <div class="form-group">
            <div class="form-text-wrap">
              <label class="form-text">番地</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :block, class: 'input-default', id: 'addresses', placeholder: '例）青山1-1-1' %>
          </div>
          <div class="form-group">
            <div class="form-text-wrap">
              <label class="form-text">建物名</label>
              <span class="form-any">任意</span>
            </div>
            <%= f.text_field :building, class: 'input-default', id: 'building', placeholder: '例）柳ビル103' %>
          </div>
          <div class="form-group">
            <div class="form-text-wrap">
              <label class="form-text">電話番号</label>
              <span class="indispensable">必須</span>
            </div>
            <%=
              f.text_field :phone_number,
                           class: 'input-default',
                           id: 'phone-number',
                           placeholder: '例）09012345678',
                           maxlength: '11'
            %>
          </div>
        </div>
        <%# /配送先の入力 %>
        <div class="buy-btn">
          <%= f.submit '購入', class: 'buy-red-btn', id: 'button' %>
        </div>
      <% end %>
    </div>
  </div>
  </div>
  <%= render 'shared/second-footer' %>

app/views/orders/refresh_card_frame.turbo_stream.erb
<%= turbo_stream.replace "card_frame" do %>
  <%= turbo_frame_tag "card_frame" do %>
    <% if @cards.present? %>
      <%= turbo_frame_tag "selected-card" do %>
        <%= render 'selected_card', selected_card: @selected_card %>
      <% end %>
    <% else %>
      <%= turbo_frame_tag "selected-card" do %>
      <div class="text-center">
        <%= link_to fa_icon('plus 2x', text: 'Add New Card'),
                        new_user_card_path(current_user, context: 'orders_top'),
                        class: 'inline-flex items-center w-full max-w-lg p-5 text-2xl font-semibold text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer justify-evenly dark:hover:text-gray-300 dark:border-gray-700 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700',
                        data: { turbo_frame: 'modal'} %>
      </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/orders/toggle_card_list.turbo_stream.erb
<%= turbo_stream.replace "card_frame" do %>
  <%= turbo_frame_tag "card_frame" do %>
    <% if @show_card_list %>
      <%= render 'card_list', locals: { cards: @cards, selected_card: @selected_card } %>
    <% else %>
      <%= render 'selected_card', selected_card: @selected_card %>
    <% end %>
  <% end %>
<% end %>