config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users
  root to: "items#index"
  post 'toggle_card_list', to: 'orders#toggle_card_list'
  resources :items do
    member do
      post   'like' => 'likes#like',   as: 'like'
      delete 'unlike' => 'likes#unlike', as: 'unlike'
    end
    resources :comments, only: :create
    resources :orders, only: [:index, :create] do
      collection do
        get 'refresh_card_frame'
        post 'set_card'
        post 'clear_session'
      end
    end
  end
  resources :users, only: :show do
    resources :cards, only: [:index, :new, :create, :destroy] do
      member do
        post 'set_default'
      end
    end
    member do
      get :likes
      get 'items'
      get 'orders'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :info, :images, presence: true
  validates :images, length: { minimum: 1, maximum: 5, message: 'は1枚以上5枚以下にしてください' }
  validates :price, presence: true,
                    numericality: {
                      only_integer: true,
                      greater_than_or_equal_to: 300,
                      less_than_or_equal_to: 9_999_999
                    }

  belongs_to :user
  has_one :order
  has_many_attached :images
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition
  belongs_to :postage_type
  belongs_to :prefecture
  belongs_to :shipping_time

  validates :category_id, :condition_id, :postage_type_id, :prefecture_id,
            :shipping_time_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_item, except: [:index, :new, :create]
  before_action :existence_check, except: [:index, :new, :create]
  before_action :contributor_confirmation, only: [:edit, :update]
  before_action :check_if_sold, only: [:edit, :update]

  def index
    @items = Item.all.order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @comments = @item.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(params[:id])
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(
      :name,
      :info,
      :category_id,
      :condition_id,
      :price,
      :postage_type_id,
      :prefecture_id,
      :shipping_time_id,
      { images: [] }
    ).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find_by(id: params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @item.user
  end

  def existence_check
    redirect_to root_path if @item.nil?
  end

  def check_if_sold
    redirect_to root_path if @item.order.present?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <% content_for :header do %>
<%= render 'shared/second-header' %>
<% end %>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, id: 'new_item', local: true do |f| %>

    <%= render 'shared/error_messages', model: @item %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div id="previews"></div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'item[images][]', data: {index: 0} %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:postage_type_id, PostageType.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_time_id, ShippingTime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', item_path(@item.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<div class="main">
  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class="text-white [text-shadow:_0_0_5px_rgb(0_0_0_/_90%)] flex flex-col items-start justify-center bg-[url('furima-header01.png')] bg-cover bg-no-repeat bg-top bg-center w-screen px-sp-3xs-5xl py-sp-l-xl">
    <h1 class="text-fs-xxl">人生を変えるフリマアプリ</h1>
    <p class="text-fs-base">FURIMAはだれでもかんたんに出品・購入できる</p>
    <p class="text-fs-base">フリマアプリです</p>
    <div class="flex mt-sp-s">
      <%= link_to image_tag('app-store.svg', class: 'mr-sp-s h-sp-xl-2xl'), '#' %>
      <%= link_to image_tag('google-play.png', class: ' h-sp-xl-2xl'), '#' %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分 %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class="select-reason-contents px-sp-3xs-5xl py-sp-l-xl">
    <h2 class="relative font-bold text-center title mb-sp-l text-fs-md after:w-sp-2xl after:h-[4px] after:bg-furimaTeal after:absolute after:bottom-[-10px] after:left-[50%] after:translate-x-[-50%]">FURIMAが選ばれる3つの理由</h2>
    <ul class="flex justify-between gap-sp-xs">
      <li class="relative flex flex-col items-center w-sp-3xl-6xl">
        <%= image_tag 'furima-intro01.png', class: 'w-full mb-5' %>
        <span class="absolute top-0 left-0 inline-flex items-center justify-center text-white text-fs-lg w-sp-l-xl h-sp-l-xl bg-furimaTeal">1</span>
        <h3 class="font-bold text-fs-md">
          <span class="text-furimaTeal">3分</span>
          ですぐに出品
        </h3>
        <p class="text-fs-base mt-sp-s">スマホで入力するだけで簡単に出品できる！</p>
      </li>
      <li class="relative flex flex-col items-center w-sp-3xl-6xl">
        <%= image_tag 'furima-intro02.png', class: 'w-full mb-5' %>
        <span class="absolute top-0 left-0 inline-flex items-center justify-center text-white text-fs-lg w-sp-l-xl h-sp-l-xl bg-furimaTeal">2</span>
        <h3 class="font-bold text-fs-md">
          <span class="text-furimaTeal">シンプル</span>
          で使いやすい
        </h3>
        <p class="text-fs-base mt-sp-s">めんどくさい入力は必要なく、検索も購入もスムーズ！</p>
      </li>
      <li class="relative flex flex-col items-center w-sp-3xl-6xl">
        <%= image_tag 'furima-intro03.png', class: 'w-full mb-5' %>
        <span class="absolute top-0 left-0 inline-flex items-center justify-center text-white text-fs-lg w-sp-l-xl h-sp-l-xl bg-furimaTeal">3</span>
        <h3 class="font-bold text-fs-md">
          手数料
          <span class="text-furimaTeal">業界最安</span>
        </h3>
        <p class="text-fs-base mt-sp-s">10%でお得に出品&購入！</p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class="text-white [text-shadow:_0_0_5px_rgb(0_0_0_/_90%)] flex flex-col items-start justify-center bg-[url('furima-header02.png')] bg-cover bg-no-repeat bg-top bg-center w-screen px-sp-3xs-5xl py-sp-l-xl">
    <h2 class="text-fs-lg mb-sp-m">会員数日本一位</h2>
    <p class="text-fs-base">FURIMAは、フリマアプリで最も人気。</p>
    <p class="text-fs-base">出品・購入回数も業界最多です！</p>
    <p class="text-fs-base">ほしかったあの商品に出会えるかもしれません。</p>
    <div class="flex mt-sp-s">
      <%= link_to image_tag('app-store.svg', class: 'mr-sp-s h-sp-xl-2xl'), '#' %>
      <%= link_to image_tag('google-play.png', class: 'h-sp-xl-2xl'), '#' %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class="px-sp-3xs-5xl py-sp-l-xl">
    <h2 class="relative font-bold text-center text-fs-md mb-sp-m after:w-sp-2xl after:h-[4px] after:bg-furimaTeal after:absolute after:bottom-[-10px] after:left-[50%] after:translate-x-[-50%]">FURIMAの特徴</h2>
    <ul class="flex flex-wrap justify-between feature-lists">
      <li class="flex flex-col items-center w-sp-3xl-5xl">
        <%= image_tag 'furima-intro04.png', class: 'list-pict' %>
        <h3 class="font-bold text-fs-md">簡単に売り買いできる</h3>
        <p class="mt-sp-s text-fs-base">スマホひとつで、いつでもどこでも簡単に出品・購入が可能！</p>
      </li>
      <li class="flex flex-col items-center w-sp-3xl-5xl">
        <%= image_tag 'furima-intro05.png', class: 'list-pict' %>
        <h3 class="font-bold text-fs-md">売上金は即日振込みに対応</h3>
        <p class="mt-sp-s text-fs-base">午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。</p>
      </li>
      <li class="flex flex-col items-center w-sp-3xl-5xl">
        <%= image_tag 'furima-intro06.png', class: 'list-pict' %>
        <h3 class="font-bold text-fs-md">様々な支払いに対応</h3>
        <p class="mt-sp-s text-fs-base">
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class="flex flex-col items-center bg-white py-sp-2xl">
    <h2 class="font-bold text-fs-lg">ピックアップカテゴリー</h2>
    <div class="font-bold text-fs-md my-sp-s text-furimaTeal">新規投稿商品</div>
    <ul class="flex flex-wrap justify-center gap-5">
      <% if @items.present? %>
        <% @items.each do |item| %>
          <li class="list">
            <%= link_to item_path(item) do %>
              <div class="relative">
                <%= image_tag(item.images[0], class: 'w-sp-5xl h-sp-5xl') %>

                <% if item.order %>
                  <div class="absolute w-full p-2 text-center -skew-y-12 bg-red-600 top-sp-2xl">
                    <span class="text-3xl text-white bold">Sold Out!!</span>
                  </div>
                <% end %>
              </div>
              <div class="text-black bg-white p-sp-xs">
                <h3 class="text-fs-base">
                  <%= item.name %>
                </h3>
                <div class="flex justify-between text-fs-xs">
                  <span><%= item.price %>円<br />
                    <%= item.postage_type.name %></span>
                  <div class="flex items-center">
                    <% if current_user && current_user.likes.find_by(item_id: item.id) %>
                       <%= fa_icon 'star lg', class: 'pr-[5px] text-yellow-400' %>
                    <% else %>
                       <%= fa_icon 'star lg', class: 'pr-[5px]' %>
                    <% end %>
                      <span class="text-fs-sm"><%= item.likes.count %></span>
                  </div>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      <% else %>
      <li class="list">
        <%= link_to '#' do %>
          <%=
            image_tag 'https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg',
                      class: 'w-sp-5xl h-sp-5xl'
          %>
          <div class="text-black bg-white p-sp-xs">
            <h3 class="text-fs-base">商品を出品してね！</h3>
            <div class="flex justify-between text-fs-xs">
              <span>99999999円<br />(税込み)</span>
              <div class="flex items-center">
                <%= fa_icon 'star lg', class: 'pr-[5px]' %>
                <span class="text-fs-sm">0</span>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to(new_item_path, class: 'fixed flex flex-col items-center justify-center text-center rounded purchase-btn w-sp-3xl h-sp-3xl bottom-sp-m right-sp-m p-sp-xs bg-furimaTeal') do %>
  <span class="block text-white purchase-btn-text text-fs-base mb-sp-3xs">出品する</span>
  <%= image_tag 'icon_camera.png', size: '185x50', class: 'w-[60%]' %>
<% end %>
<%#= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <% content_for :header do %>
<%= render 'shared/second-header' %>
<% end %>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, id: 'new_item', local: true do |f| %>

    <%= render 'shared/error_messages', model: @item %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div id="previews"></div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'item[images][]', data: {index: 0} %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:postage_type_id, PostageType.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_time_id, ShippingTime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/show.html.erb
<%# 商品の概要 %>
<div class="bg-[#f8f8f8] flex flex-col items-center sm:p-sp-l w-screen">
  <div class="flex flex-col items-center w-full bg-white sm:w-3/4 min-w-fit sm:px-sp-3xs-5xl py-sp-s-l">
    <h2 class="font-bold text-center text-fs-md">
      <%= @item.name %>
    </h2>
    <div class="relative item-img-content">
      <%= image_tag(@item.images[0], class:"w-full max-w-[448px] min-h-[448px] max-h-[448px] aspect-square item-box-img", id:"main-img") %><br>
      <% if @item.order %>
        <div class="absolute w-full p-2 text-center -skew-y-12 bg-red-600 top-52">
          <span class="text-5xl text-white bold">Sold Out!!</span>
        </div>
      <% end %>
      <div class="thumbnail-images">
        <% @item.images.each_with_index do |image, index| %>
          <div class="thumbnail-image">
            <%= image_tag image, class: (index == 0 ? 'active-thumbnail' : '') %>
          </div>
        <%end%>
      </div>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥<%= @item.price %>
      </span>
      <span class="item-postage">
        <%= @item.postage_type.name %>
      </span>
    </div>

    <% if user_signed_in? && @item.order.blank? %>
      <% if current_user.id == @item.user_id %>
        <%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
          <p class="or-text">or</p>
        <%= link_to "削除", item_path(@item.id), data: { turbo_method: :delete }, class:"item-destroy" %>
      <% else %>
        <%= link_to "購入画面に進む", item_orders_path(@item.id) ,class:"item-red-btn"%>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.postage_type.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.shipping_time.name %></td>
        </tr>
      </tbody>
    </table>
    <% if current_user %>
    <div class="option">
      <%= turbo_frame_tag "like-link-#{@item.id}", class: "inline-flex items-center mr-5" do %>
        <%= render 'likes/like', item: @item %>
      <% end %>
      <div class="py-2 report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
    <% end %>
  </div>
  <%# /商品の概要 %>

  <div id="comments">
    <h4 class="font-bold text-fs-md m-sp-xs">＜コメント一覧＞</h4>
    <% @item.comments.each do |comment| %>
      <div class="flex gap-1">
        <p class="m-0 font-bold text-gray-500"><%= comment.user.nickname %>: </p>
        <p class="m-0"><%= comment.text %></p>
      </div>
    <% end %>
  </div>

  <div class="w-full text-center bg-white m-sp-l sm:max-w-lg">
    <% if user_signed_in? %>
      <%= form_with model: [@item, @comment], id: "comment-form" do |f| %>
        <%= f.text_area :text, class: "w-full h-[100px] p-[10px] resize-none border-2 border-[#dedede]" %>
        <p class="text-center sm:text-left p-sp-2xs my-sp-2xs text-fs-sm">
          相手のことを考え丁寧なコメントを心がけましょう。
          <br>
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        </p>
        <%= f.button :submit, class: "rounded-full mb-3 p-sp-xs text-white w-1/2 min-w-[150px] border border-furimaTeal bg-furimaTeal text-fs-base" do %>
          <div class="flex justify-center gap-2">
          <%= image_tag "comment.png", class: "mb-1", width: "20", height: "25" %>
          <span>コメントする<span></div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= @item.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>