config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users
  root to: "items#index"
  post 'toggle_card_list', to: 'orders#toggle_card_list'
  resources :items do
    member do
      post   'like' => 'likes#like',   as: 'like'
      delete 'unlike' => 'likes#unlike', as: 'unlike'
    end
    resources :comments, only: :create
    resources :orders, only: [:index, :create] do
      collection do
        get 'refresh_card_frame'
        post 'set_card'
        post 'clear_session'
      end
    end
  end
  resources :users, only: :show do
    resources :cards, only: [:index, :new, :create, :destroy] do
      member do
        post 'set_default'
      end
    end
    member do
      get :likes
      get 'items'
      get 'orders'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  attr_accessor :token

  validates :token, presence: true, on: :create
  encrypts :brand, :last4, :exp_month, :exp_year

  # Expiration Date Check
  def expired?
    Date.new(exp_year.to_i, exp_month.to_i, 1) < Date.today
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :user_existence_check
  before_action :contributor_confirmation

  def index
    @cards = current_user.cards
  end

  def new
  end

  def create
    result = Cards::CreateService.new(user: current_user, token: params[:token]).call

    if result.success?
      @card = result.card
      respond_to do |format|
        format.turbo_stream do
          if params[:context] == 'orders_top'
            @selected_card = @card
            render turbo_stream: turbo_stream.update('selected-card', partial: 'orders/selected_card',
                                                                      locals: { selected_card: @selected_card })
          elsif params[:context] == 'orders_card_list'
            render turbo_stream: turbo_stream.append('cards-container', partial: 'orders/new_card',
                                                                        locals: { cards: @cards, selected_card: @selected_card })
          else
            render turbo_stream: [
              turbo_stream.update('flash', partial: 'shared/flash_messages', locals: { notice: 'Card added' }),
              turbo_stream.append('cards-list', partial: 'cards/card', locals: { card: @card })
            ]
          end
        end

        format.html do
          redirect_to user_cards_path(current_user), notice: 'Card successfully added.'
        end
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    card = Card.find_by(id: params[:id], user_id: current_user.id)
    redirect_to user_cards_path(current_user), alert: 'Card not found.' and return if card.nil?

    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    begin
      customer = Payjp::Customer.retrieve(current_user.payjp_customer_id)
      customer_card = customer.cards.retrieve(card.card_id)
      customer_card.delete if customer_card.present?
      card.destroy
      customer = Payjp::Customer.retrieve(current_user.payjp_customer_id)
      new_default_card = customer.default_card
      if new_default_card != card.card_id
        new_default_card = current_user.cards.find_by(card_id: new_default_card)
        new_default_card&.update(is_default: true)
      end
      flash[:notice] = 'Card successfully deleted.'
      redirect_to user_cards_path(current_user)
    rescue Payjp::CardError => e
      flash[:alert] = "Failed to delete card: #{e.message}"
      redirect_to user_cards_path(current_user)
    end
  end

  def set_default
    Card.transaction do
      # Reset the default status of all cards
      current_user.cards.update_all(is_default: false)

      # Set the new default card
      card = current_user.cards.find_by(id: params[:id])
      if card
        Payjp.api_key = ENV['PAYJP_SECRET_KEY']
        customer = Payjp::Customer.retrieve(current_user.payjp_customer_id)
        customer.default_card = card.card_id
        if customer.save
          card.update!(is_default: true)
          redirect_to user_cards_path(current_user), notice: 'Default card updated successfully.'
        else
          redirect_to user_cards_path(current_user), alert: 'Failed to update default card on Payjp.'
        end
      else
        redirect_to user_cards_path(current_user), alert: 'Card not found.'
      end
    end
  rescue StandardError => e
    redirect_to user_cards_path(current_user), alert: "Failed to update default card: #{e.message}"
  end

  private

  def set_user
    @user = User.find_by(id: params[:user_id])
  end

  def user_existence_check
    redirect_to root_path if @user.nil?
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @user
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div class="mb-3">
  <div
    class="relative inline-flex items-center justify-between w-full max-w-xl p-5 text-gray-500 bg-white border <%= card.is_default ? ' border-green-500' : ' border-gray-200' %> rounded-lg dark:border-gray-700 dark:text-gray-400 dark:bg-gray-800"
  >
    <%= fa_icon "cc-#{card.brand.downcase} 3x", class: 'w-1/4' %>
    <div class="block w-2/4">
      <% if card.is_default? %>
        <p
          class="absolute inset-0 items-center justify-center w-1/6 h-4 text-xs text-white bg-green-500 rounded rounded-tr-none rounded-bl-none"
        >
          Default
        </p>
      <% end %>
      <div class="w-full text-lg font-semibold"><%= "**** **** **** #{card.last4}" %></div>
      <div class="w-full">Expires on <%= card.exp_month %>/<%= card.exp_year %></div>
    </div>
    <div class="flex items-center justify-end w-1/4">
      <% unless card.is_default %>
        <%=
              button_to set_default_user_card_path(current_user, card),
                        method: :post,
                        class: 'p-1 text-xs text-white bg-green-500 border border-green-500 rounded' do
            %>
          Set<br />Default
        <% end %>
      <% end %>
      <%=
            button_to user_card_path(current_user, card),
                      method: :delete,
                      data: {
                        confirm: 'Are you sure?',
                      },
                      class: 'p-1 ml-1 text-xs text-white bg-red-700 border border-red-700 rounded' do
          %>
        Delete <br />
        Card
      <% end %>
    </div>
  </div>
</div>

app/views/cards/_card_form.html.erb
<%= render "shared/modal" do %>
  <h1 class="text-2xl font-bold text-center">カード登録</h1>
  <%= form_with url: user_cards_path, id: 'charge-form', class: 'card-form', data: { controller: "card", "card-context-value" => @context, "card-target": "form"} do |f| %>
    <div class="relative mt-4">
      <label for="number-form" class="text-xs">カード番号</label>
      <div
        id="number-form"
        class="pl-2 mb-3 border border-gray-300 border-solid rounded"
        data-card-target="number"
      ></div>
    </div>
    <div class="flex justify-between mb-3">
      <div class="w-full mr-2.5">
        <label for="expiry-form" class="text-xs">有効期限</label>
        <div id="expiry-form" class="pl-2 border border-gray-300 border-solid rounded" data-card-target="expiry"></div>
      </div>
      <div class="w-full ml-2.5">
        <label for="cvc-form" class="text-xs">CVC</label>
        <div id="cvc-form" class="pl-2 border border-gray-300 border-solid rounded" data-card-target="cvc"></div>
      </div>
    </div>
    <%= hidden_field_tag :context, params[:context] %>
    <div class="flex justify-center">
      <%=
        f.submit '登録する',
                 class:
                   'w-full p-2 font-semibold text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-300 focus:ring-offset-2',
                 id: 'new-card-button'
      %>
    </div>
  <% end %>
<% end %>

app/views/cards/_cards_list.html.erb
<% if cards.present? %>
  <% cards.each do |card| %>
    <div class="mb-3">
      <div
        class="relative inline-flex items-center justify-between w-full max-w-xl p-5 text-gray-500 bg-white border <%= card.is_default ? ' border-green-500' : ' border-gray-200' %> rounded-lg dark:border-gray-700 dark:text-gray-400 dark:bg-gray-800"
      >
        <%= fa_icon "cc-#{card.brand.downcase} 3x", class: 'w-1/4' %>
        <div class="block w-2/4">
          <% if card.is_default? %>
            <p
              class="absolute inset-0 items-center justify-center w-1/6 h-4 text-xs text-white bg-green-500 rounded rounded-tr-none rounded-bl-none"
            >
              Default
            </p>
          <% end %>
          <div class="w-full text-lg font-semibold"><%= "**** **** **** #{card.last4}" %></div>
          <div class="w-full">Expires on <%= card.exp_month %>/<%= card.exp_year %></div>
        </div>
        <div class="flex items-center justify-end w-1/4">
          <% unless card.is_default %>
            <%=
              button_to set_default_user_card_path(current_user, card),
                        method: :post,
                        class: 'p-1 text-xs text-white bg-green-500 border border-green-500 rounded' do
            %>
              Set<br />Default
            <% end %>
          <% end %>
          <%=
            button_to user_card_path(current_user, card),
                      method: :delete,
                      data: {
                        confirm: 'Are you sure?',
                      },
                      class: 'p-1 ml-1 text-xs text-white bg-red-700 border border-red-700 rounded' do
          %>
            Delete <br />
            Card
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/cards/index.html.erb
<% content_for :sidebar do %>
  <%= render 'shared/sidebar' %>
<% end %>
<%= include_gon %>
<div class="content">
  <h2 class="mb-3">クレジットカード一覧</h2>
  <%= turbo_frame_tag 'cards-list' do %>
    <%= render 'cards_list', cards: @cards %>
  <% end %>
  <div class="text-center">
    <%=
      link_to fa_icon('plus 2x', text: 'Add New Card'),
              new_user_card_path,
              class:
                'inline-flex items-center w-full max-w-xl p-5 text-2xl font-semibold text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer justify-evenly dark:hover:text-gray-300 dark:border-gray-700 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700',
              data: {
                turbo_frame: 'modal',
              }
    %>
  </div>
</div>

app/views/cards/new.html.erb
<% content_for :sidebar do %>
  <%= render 'shared/sidebar' %>
<% end %>

<div class="content">
  <section class="mdc" id="v2-mdc">
    <%= render 'card_form' %>
  </section>
</div>